openapi: 3.1.0
info:
  version: 0.1.0
  title: Turing Signing Server Reference Documentation
  contact:
    url: "https://tss.stellar.org/"
  license:
    name: GPL-3.0 License
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
  x-logo:
    url: "https://raw.githubusercontent.com/tyvdh/stellar-turrets/master/assets/tss-logo.png"
    altText: Stellar Turrets Home Page
  description: >
    Stellar Turrets provide decentralizated contract creation on Stellar.
tags:
  - name: Turret
    description: View information about a Turret
  - name: txFunctions
    description: >
      Manage and run txFunctions on the Turret. A txFuntion is a JavaScript file that outputs a valid Transaction Envelope XDR.
      The txFunction will be executed in a node environment with the following default node_module packages:
        * bignumber.js
        * node-fetch
        * stellar-sdk
  - name: Fees
    description: >
      Manage and view Fee Balances on the Turret. A Fee Balance is an XLM based balance that the Turret will accrue fees against as txFunctions are run.
      A Fee Balance is unique to a Stellar account Public Key.
  - name: Control Accounts
    description: Control Turret accounts.
paths:
  /:
    $ref: "paths/root.yml"
  /.well-known/stellar.toml:
    $ref: "paths/well-known/toml.yml"
  /tx-functions:
    $ref: "paths/tx-functions.yml"
  /tx-functions/{txFunctionHash}:
    $ref: "paths/tx-functions@{txFunctionHash}.yml"
  /tx-fees:
    $ref: "paths/tx-fees.yml"
  /tx-fees/{publicKey}:
    $ref: "paths/tx-fees@{publicKey}.yml"
  /ctrl-accounts:
    $ref: "paths/ctrl-accounts.yml"
components:
  securitySchemes:
    XdrToken:
      $ref: "auth/XdrToken.yml"
servers:
  - url: "http://valid-turret-address"
